[package]
name = "poll"
version = "0.1.0"
authors = ["Indiana Kernick <indiana.kernick@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "0.2", features = ["full"] }
warp = { version = "0.2", features = ["tls"] }
log = "0.4"
pretty_env_logger = "0.4"
askama = "0.10"
askama_warp = "0.10"
# Using tokio-postgress 0.5 because it uses tokio 0.2.
# Later versions have switched to tokio 0.3 but
# warp is not compatible with tokio 0.3
tokio-postgres = { version = "0.5", features = ["with-chrono-0_4"] }
deadpool-postgres = { version = "0.5" }
serde = { version = "1.0", features = ["derive"] }
rand = "0.7"
csv = "1"
futures = "0.3"
qrcode = { version = "0", default-features = false }
png = "0"

[profile.release]
lto = true
